### PR TITLE
Merge pull request #20 from Frontrider/0.1.0-release

### PR DESCRIPTION
**Pull request by Frontrider**
merging last modifications and triggering a build

### CODE REVIEW

**Comment by enderger** [comment]
A working build.gradle is in my pull request.

**Comment by enderger** [comment]
Build fails without my modifications

**Comment by Frontrider** [comment]
And I'll set up locks on the main branch, so you'll never be able to trigger a build.

**Comment by Frontrider** [comment]
I also did some refactoring in my build.gradle, that moves these into the properties file. so, I'd prefer if that file was not in the request. Also, make the request into 0.1.0.

**Comment by Frontrider** [comment]
I'd also prefer that since the CI server will automatically deploy any commits sent to the master branch.

**Comment by Frontrider** [comment]
Closing it, I will not be able to merge it because of the build file.

**Pull request closed without merging**
